INHERIT: mkdocs-base.yaml
site_name: "Dynatrace Observability Workshop — EasyTrade"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-wwse/codespaces-framework"
nav:
  - 'Welcome': index.md
  - 'Pre-requisites': pre-requisites.md
  - '1. Dynatrace Operator & Agent': setup-dynatrace.md
  - '2. EasyTrade Installation': setup-easytrade.md
  - '3. Platform Walkthrough': platform-walkthrough.md
  - '4. Use Case 1 — DB Not Responding': usecase1-db-not-responding.md
  - '5. Use Case 2 — High CPU Usage': usecase2-high-cpu.md
  - '6. Use Case 3 — Dashboarding': usecase3-dashboarding.md
  - 'Cleanup': cleanup.md
  - 'References': references.md
extra:
  rum_snippet: "https://js-cdn.dynatrace.com/jstag/1612cf70810/bf81393wlb/ff78563295ff1e42_complete.js"
